export const products = [
  {
    id: 1,
    name: "Wireless Headphones",
    description: "Noise-cancelling over-ear headphones.",
    price: 129.99,
    category: "Electronics",
    image: "https://picsum.dev/300/300?random=1",
    inStock: true,
    rating: 4.5,
    numberOfProducts: 10,
    type: "product",
  },
  {
    id: 2,
    name: "Smartphone",
    description: "Latest Android phone with 128GB storage.",
    price: 699.99,
    category: "Electronics",
    image:
      "https://placeholder.vn/placeholder/300x300?bg=3b82f6&color=ffffff&text=Smartphone",
    inStock: true,
    rating: 4.8,
    numberOfProducts: 7,
    type: "product",
  },
  {
    id: 3,
    name: "Running Shoes",
    description: "Lightweight, stylish running shoes.",
    price: 89.99,
    category: "Fashion",
    image: "https://picsum.dev/300/300?random=2",
    inStock: false,
    rating: 4.2,
    numberOfProducts: 6,
    type: "product",
  },
  {
    id: 4,
    name: "Gaming Mouse",
    description: "RGB gaming mouse with 7 buttons.",
    price: 49.99,
    category: "Accessories",
    image:
      "https://placeholder.vn/placeholder/300x300?bg=059669&color=ffffff&text=Gaming+Mouse",
    inStock: true,
    rating: 4.6,
    numberOfProducts: 8,
    type: "product",
  },
  {
    id: 5,
    name: "Coffee Maker",
    description: "Programmable drip coffee machine.",
    price: 149.99,
    category: "Home Appliances",
    image: "https://picsum.dev/300/300?random=3",
    inStock: true,
    rating: 4.4,
    numberOfProducts: 7,
    type: "product",
  },

  {
    id: 6,
    name: "Node.js lecture",
    description: "AI Based Node.js Course 1 day availablity",
    price: 10,
    category: "Courses",
    image: "https://download.logo.wine/logo/Node.js/Node.js-Logo.wine.png",
    inStock: true,
    rating: 4.4,
    type: "service",
  },

  {
    id: 7,
    name: "Reactjs lecture",
    description: "AI Based Reactjs Course 1 day availablity.",
    price: 15,
    category: "Courses",
    image:
      "https://download.logo.wine/logo/React_(web_framework)/React_(web_framework)-Logo.wine.png",
    inStock: true,
    rating: 4.4,
    type: "service",
  },

  {
    id: 8,
    name: "AWS lecture",
    description: "AI Based AWS Course 1 day availablity.",
    price: 20,
    category: "Courses",
    image:
      "http://download.logo.wine/logo/Amazon_Web_Services/Amazon_Web_Services-Logo.wine.png",
    inStock: false,
    rating: 4.4,
    type: "service",
  },
  {
    id: 9,
    name: "Python lecture",
    description: "AI Based Python Course 1 day availablity.",
    price: 25,
    category: "Courses",
    image:
      "https://download.logo.wine/logo/Python_(programming_language)/Python_(programming_language)-Logo.wine.png",
    inStock: true,
    rating: 4.4,
    type: "service",
  },
];
